add_newline = false

format = """
$hostname\
$character\
$sudo\
$git_branch\
$git_commit\
$git_state \
$directory » """

[username]
format = "[$user]($style)"
show_always = true

[hostname]
format = "[$ssh_symbol]($style)"
ssh_only = true
ssh_symbol = ""
style = "bold dimmed blue"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%Y.%m.%d %H:%M:%S"

[character]
format = "$symbol"
success_symbol = "‹[0](green)›"
error_symbol = "‹[!](bold red)›"

[directory]
format = "[$path]($style)"
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = " ‹[$branch(:$remote_branch)]($style)›"

[git_commit]
format = " ‹[$hash]($style)›"

[git_state]
format = " ‹[$state( $progress_current/$progress_total)]($style)›"

[sudo]
disabled = false
format = " ‹[$symbol]($style)›"
symbol = "sudo"
