[git.files]
git = "~/.config/git"

[git.variables]
git_email = "jshuay@gmail.com"
git_name = "jshuay"

[wezterm.files]
wezterm = "~/.config/wezterm"

[fish.files]
fish = "~/.config/fish"

[starship.files]
starship = "~/.config/starship"

[bin.files]
bin = "~/bin"

[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }
