[git.files]
git = "~/.config/git"

[git.variables]
git_email = "jshuay@gmail.com"
git_name = "jshuay"

[wezterm.files]
wezterm = "~/.config/wezterm"

[wezterm.variables]
wezterm_default_domain = "local"
